### ISSUE TITLE
SpecMapPercentageChance per driver

### ISSUE THREAD

**Issue by Fuel44** [Robertsmania/iRacingEquanimityPaint#1]
Have it apply to each driver rather than the entire field

**Comment by Fuel44** [comment]
Never mind on this one...I forgot that I need them all to look the same. :)

**Comment by Fuel44** [comment]
Oops

**Comment by Robertsmania** [comment]
Is this still something you want?

Personally, I think that goes against the idea of the equanimity paint philosophy, making some drivers appear different from others. It seems more appropriate to me to have either everyone get the spec map or nobody does.
