### ISSUE TITLE
CarSpecificHelmetSuit logic is reversed

### ISSUE THREAD

**Issue by Fuel44** [Robertsmania/iRacingEquanimityPaint#3]
When CarSpecificHelmetSuit is false, it still looks for the common tga file in the car folder rather than the general "Helmet" or "Suit" folders.

**Comment by Robertsmania** [comment]
Hmm, thats not what I see.  Here is the output when the option is false, it tries to copy from paintcommon hemet|suit

```
CarSpecificHelmetSuit: False
OnlyRaces: True

Use Spec Map: True

New Session! 68519368
Added new driver # 1 with car path: raygr22 UserID: 494644
Common file does not exist: C:\Users\Kris\Documents\iRacing\paintcommon\helmet\helmet_common.tga
Common file does not exist: C:\Users\Kris\Documents\iRacing\paintcommon\suit\suit_common.tga
```

When its true it tries to copy from the car directory:
```
CarSpecificHelmetSuit: True
OnlyRaces: True

Use Spec Map: True

New Session! 68519368
Added new driver # 1 with car path: raygr22 UserID: 494644
Common file does not exist: C:\Users\Kris\Documents\iRacing\paintcommon\raygr22\helmet_common.tga
Common file does not exist: C:\Users\Kris\Documents\iRacing\paintcommon\raygr22\suit_common.tga
```

The option determines where the files are copied from, but the destination is always the \paints\carname folder so it overrides any other helmet|suit files elsewhere in other paint folders.

**Comment by Fuel44** [comment]
My bad!
