### ISSUE TITLE
Late arriving drivers

### ISSUE THREAD

**Issue by Fuel44** [Robertsmania/iRacingEquanimityPaint#5]
The program applies common files to the registered drivers, regardless if drivers have joined the session or not. It appears that when the common files as marked as read only, it will block iRacing from overwriting the common files when the driver joins the session. It might be a good idea for the program to mark it as read only as it copies it over, just in case the common files are not read only?

**Comment by Robertsmania** [comment]
Fixed in afc722fad90a0585011f126bf876ee649ae0839f
