### ISSUE TITLE
RandomPerDriver - Hide Car Number

### ISSUE THREAD

**Issue by Fuel44** [Robertsmania/iRacingEquanimityPaint#9]
It would be handy to have an additional random per driver mode - one without car numbers.

**Comment by Robertsmania** [comment]
Please post the code you added to support this?

**Comment by Fuel44** [comment]
if (startArg.StartsWith("RandomPerDriver")) 
{
    SetupRandomFiles();
}

**Comment by Fuel44** [comment]
P.S. so, now I have a "RandomPerDriver" argument (show number) and a "RandomPerDriver_NoNumber" argument. 

The { "car_num", startArg == "RandomPerDriver" ? "car_common.tga" : "car_num_common.tga" }, code works as is, so I only had to adjust the code that I sent in my previous message.

Keep in mind that I'm just trying to get it to work as quickly as I can so that I can see if it's something worth bringing up as an issue. I'm sure you'll have a cleaner/acceptable approach to accomplishing the same.

**Comment by Robertsmania** [comment]
Ahh, I think I get it now!

**Comment by Robertsmania** [comment]
I'd like to split the options so they could be used independently, and in other modes.

Lets see if this makes sense for how you would use them:

RandomPerDriver - does the random setup per driver, but doesnt explicitly change the car/num texture behavior.

IgnoreCarNumFile - changes the behavior to determine whether to produce a car_num_UserId.tga file at all.  Defaults to false, so if unspecified it does copy the num file.  If its true, its like useSpecMap and deletes any existing car_num_UserId.tga (if it was there from a previous run).

So to get your previous behavior for random drivers that show their sim-stamped numbers you would use:
RandomPerDriver IgnoreCarNumFile

And the new behavior that hides the sim-stamped numbers with random paints for each driver:
RandomPerDriver

Both of these will be added to the Options.json so you could set them in the file, but if you provide them on the command line - it overrides whats loaded from the file for that run.

**Comment by Fuel44** [comment]
BrilliantOn May 10, 2024, at 9:00 AM, Kris ***@***.***> wrote:﻿
I'd like to split the options so they could be used independently, and in other modes.
Lets see if this makes sense for how you would use them:
RandomPerDriver - does the random setup per driver, but doesnt explicitly change the car/num texture behavior.
IgnoreCarNumFile - changes the behavior to determine whether to produce a car_num_UserId.tga file at all.  Defaults to false, so if unspecified it does copy the num file.  If its true, its like useSpecMap and deletes any existing car_num_UserId.tga (if it was there from a previous run).
So to get your previous behavior for random drivers that show their sim-stamped numbers you would use:
RandomPerDriver IgnoreCarNumFile
And the new behavior that hides the sim-stamped numbers with random paints for each driver:
RandomPerDriver
Both of these will be added to the Options.json so you could set them in the file, but if you provide them on the command line - it overrides whats loaded from the file for that run.

**Comment by Fuel44** [comment]
Brilliant

**Comment by Robertsmania** [comment]
Okay, so I setup most of the other options that made sense to support command line overrides as well.

When you run it, the output at the start will show:
```
C:\Users\Kris\source\repos\iRacingEquanimityPaint\iRacingEquanimityPaint\bin\Debug\net7.0-windows>iRacingEquanimityPaint.exe RandomPerDriver IgnoreCarNumFile

Robertsmania iRacingEquanimityPaint started. Press Q to quit. R to force a re-run.
Use Ctrl-R in game to force the paints to update.

Optional command line arguments: iRacingPaints, RandomMode, RandomPerDriver, IgnoreCarNumFile, QuitAfterCopy, OnlyRaces, DeletePaintsFolder

Options from file:
RandomMode: True
RandomPerDriver: False
IgnoreCarNumFile: False
OnlyRaces: False
QuitAfterCopy: True
DeletePaintsFolder: True
SpecMapPercentageChance: 50
CarSpecificHelmetSuit: False
LogToFile: True
RandomMode is enabled, so CarSpecificHelmetSuit and SpecMapPercentageChance are ignored.
Command line argument: RandomPerDriver forced RandomMode/RandomPerDriver to TRUE for this run.
Command line argument: IgnoreCarNumFile forced to TRUE for this run.
```

So hopefully its clear what the command line options are, what got loaded from the Options.json file and what its using for this run...

**Comment by Robertsmania** [comment]
Fixed in 7de0e57414eb54437890ed5f4dfa0ea73116e71a

**Comment by Fuel44** [comment]
I have all of my texture files stored in the car_num folder. So, with the RandomPerDriver IgnoreCarNumFile, it's skipping the car texture copy altogether ("No files found in random_source\car - skipping"). I could maintain duplicate files in each to solve this.

BTW, this actually created an unintended consequence that I think will be another cool mode - iRacing Paints with irEP assigned spec maps. In other words, the drivers don't have a car or car_num file in paint\[Car ID] folder, but they have spec, suit and helmet files. I've always thought that this would be a cool feature for iRacing and TP to have - for a user to be able to assign a spec map that would be used for any driver in the field that only has iRacing paint.

**Comment by Fuel44** [comment]
![TruckChrome](https://github.com/Robertsmania/iRacingEquanimityPaint/assets/168591104/ce34bb34-cea0-4ff0-8380-5a517a066ea5)
![Truck](https://github.com/Robertsmania/iRacingEquanimityPaint/assets/168591104/ba1677a8-dab1-44be-98dd-ff56525528c0)

**Comment by Robertsmania** [comment]
This is making my head hurt.  But I think I see now.

When you had:
> I have a "RandomPerDriver" argument (show number) and a "RandomPerDriver_NoNumber" argument.
> 
> The { "car_num", startArg == "RandomPerDriver" ? "car_common.tga" : "car_num_common.tga" }, code works as is, so I only had to adjust the code that I sent in my previous message.

What I observed was that the output had no car_num files, nor were there car_num files in random_selection and I thought it was double copying the car_common file twice.  But now I realize it was copying car_common first and then car_num_common on top of that - so the source file really was your car_num file...  Sigh.

The IgnoreCarNumFIle option and behavior makes sense to me, but I now see that its not what you had before.

Are you willing to copy the files into both random_source/car and random_source/car_num and have the logic as is decide which files to use?  Alternatively we can try and come up with an option description that makes it clear CopyCarNumAsCarButCallCarNotNumber ?

**Comment by Fuel44** [comment]
Absolutely, I'm fine with copying the files into both - it's such a one-off use case, that I have.
